name: Deploy Hexo to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@47.92.238.44 "cd /www/wwwroot/blog.bornforthis.cn && git pull origin master && npm install && npm run build"
        #   ssh -o StrictHostKeyChecking=no root@47.92.238.44 "cd /www/wwwroot/blog.bornforthis.cn && git pull origin master && npm install && npm run build"
