name: Deploy Hexo to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node.js 22.4.1
        uses: actions/setup-node@v4
        with:
          node-version: "22.4.1"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build Hexo
        run: npm run build
      - name: Configure Git
        run: |
          git config --global user.name "AndersonHJB"
          git config --global user.email "aiyuechuang@gmail.com"
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 47.92.238.44 >> ~/.ssh/known_hosts
          git init
          git remote add deploy ssh://root@47.92.238.44:/www/wwwroot/blog.bornforthis.cn/hexo-deploy.git
          git add -A
          git commit -m "Deploy to server"
          git push -f deploy master
